apiVersion: v1
data:
    a789b468-5be5-4fde-8a6f-61209b2ab95c.json: ENC[AES256_GCM,data:LeFxEX5n91ALlsJLrF7Z9J6Kn6/6V6nPXaSO+Qea3IwqywYyqReUZ+3EVOZLuzBUHH5beJBWMDzf6GH4eRLCeRimcXNXfGO1C4WIZ+40ZshMCIgXRdpmRz50cYPutlBVyzlf4JVKdqxpckJz9bwUMO4NyNgFSth0Jwn4epR3D5HVfST8QjAySW1dAC9lltutzqVEZTNxVlFlkw4mP6zJdWssH4qzceYEg+fSUctvp0NDN3di4Tl3XhHR+VQbeNz3GWKfo37bDXVqXhdxk9yvtexbXujn/ptJJRkRr7RwCtqPRD6ZIXydPHoC0Hk=,iv:BLksfo3Ze9c5PUVGvxkCa1hilSpkY80Kj7NMhgE5ZJc=,tag:Ux8Eu9Tu7EuL7eqC+dwJTA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9lcurmwxwe8mpvsr62hluzx988e8ypjhzwykd89rvauwpjn7sxsdh77lq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUkJ0bVEyVlRvaE1NdUg4
            TXF4MGlsRXR4U1RxaTRobGhJYlJJcElkd0VZCmZOdXNOTWhCT1VONDkvRVFxd2xI
            TGs3NUxMTzQ0cUVnY25CSUxGVHNUUzAKLS0tIFU1b0Z3S0pSN3dDZ1JQZFhRYjRY
            eS9JS0pXUm1acFg0ZVlzamdmQzdlOGMKKERjwzaELAAWizVNRoIrPZRIpUwZkgt1
            3nZQxr/QfOpvRml9dJVB5V7jN682ibj5esWmc4HCDovO2zm2HdpDhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T19:19:00Z"
    mac: ENC[AES256_GCM,data:wzU5aYri8dkdF++wkwYjMt1ea+yKc6TkkpdN3Bm1s45IWRHCfuSx8S6ijHoVJX8vmBCS+gi/RBlHbvI3qbEqldVSdcKvlR+QCwNsv6yzSP1jN/neTb+OyoGA8niInt2el3BxulnLD25R1uvzmLeRT/aLwA16g6KaIZ1YD1HLZj0=,iv:faZttwiMXSBKXYhgNk8tvQP73+3fbWpRBRQ+5i2d5qc=,tag:UmfOGgJG67fM5bKGKlsW0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
