apiVersion: v1
data:
    password: ENC[AES256_GCM,data:TTDl9TfmntBDM4pFPtJIlA==,iv:si/AdmCMAcowTJL/Ud/9LXU1BfOaKqqYFNMnqNMnYx8=,tag:Yve1Pf3+9uKZh414Siuujw==,type:str]
    user: ENC[AES256_GCM,data:OaIOr6E1nQs=,iv:cWnb27jfuJDqhcd2tmR1auYMfYe+olGz6Dn5M4u3Iaw=,tag:6uxqkcyPWJWpTsJWcJr8xw==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9lcurmwxwe8mpvsr62hluzx988e8ypjhzwykd89rvauwpjn7sxsdh77lq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwalJkVEV2Ly9NVGtaRGND
            TkZ5M0ZPL2pnYmlQOFliWVpzSjNqZXlXenc0CnJYWWtzQjZoNlVWcS81N2dLakFi
            clgwVjVycXhlVDg4WURBMTBKMlZac2MKLS0tIFBFRkRVWE5ZU1pBWXRJRHdnNHI0
            ZGhHUHJLRDBDQkZTZkIwSEU5bzB0ZGcKBAYPzzFYWyqdfbFeBonnDLpDqW596e8d
            uuMvVrNQ385XbrRNk3+0l6sH03YqiWohe1Qvr3UJ6bLnzbj2I1QBZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T18:14:37Z"
    mac: ENC[AES256_GCM,data:oMwdNrzImAsTO8Tlj77sTo4WTWn9vrEp+UvYi/PyZwPIFw2ZoN0ogsYy3i48m/QvGJh45WsEYHFgwfSnbuAVq8BjXtcI1rnAUtpY876XfY2/FvqDAT6R0i7k/frcsW7Jvxg08FWBLfEVJtdWJRdUD/AAP5XFzLTmknJsasRwcAE=,iv:POwcvCWGsAihcWPC9rWQoSBMusuX3adUMde6EqEvt/Q=,tag:Z5LUctN2kZS/y5qh9xBuRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
