apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.31.0
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: data-pvc
              mounthPath: /etc/linkding/data

      volumes:
        - name: data-pvc
          PersistentVolumeClaim:
            ClaimName: linkding-pvc
