apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
namespace: linkding
spec:
  securityContext:
    runAsUser: 33
    runAsGroup: 33
    fsGroup: 33
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.31.0S
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: data-pvc
              mountPath: /etc/linkding/data
              securityContext:
          allowPrivilegeEscalation: false

      volumes:
        - name: data-pvc
          persistentVolumeClaim:
            claimName: linkding-pvc
